POST http://localhost:3003/api/blogs
Content-Type: application/json
{
    "title": "Ada Lovelace",
    "author": "37463856784365",
    "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet#tehtavat-4-1-4-2",
    "likes": 54
}