POST http://localhost:3003/api/blogs
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVkZmdoa2thaSIsImlkIjoiNjU5YjEwOTJlMjk5M2U3NTViZWU2OWVkIiwiaWF0IjoxNzA0NjY0NzMyfQ.nUxISBfcCX9Wel5m879hEWxCJZdo2UDJzMyrqqhaavA

{
    "title": "Olllli Lovelace",
    "author": "miikko",
    "url": "https://fullstackopen.com/osa4/sovelluksen_rakenne_ja_testauksen_alkeet#tehtavat-4-1-4-2",
    "likes": 54,
    "userId": "659acd79bbb5cceed9b8164c"
}